baseURL = "/"
languageCode = "en-us"
title = "36th Street"
theme = "minimal"
#disqusShortname = "username" # delete this to disable disqus comments
googleAnalytics = "UA-109529121-1"

[params]
    author = "Joey Ruan"
    description = "A Choose Your Own Adventure Story"
    githubUsername = "#"
    accent = "red"
    showBorder = true
    backgroundColor = "white"
    font = "Raleway" # should match the name on Google Fonts!
    highlight = true
    highlightStyle = "solarized-dark"
    highlightLanguages = ["go", "haskell", "kotlin", "scala", "swift"]

[[menu.main]]
    url = "/"
    name = "Home"
    weight = 1

[[menu.main]]
    url = "/1/"
    name = "Start"
    weight = 2

[[menu.main]]
    url = "/creators/"
    name = "Creators"
    weight = 3

# Social icons to be shown on the right-hand side of the navigation bar
# The "name" field should match the name of the icon to be used
# The list of available icons can be found at http://fontawesome.io/icons/

[[menu.icon]]
    url = "mailto:joseph.ruan@misd400.org"
    name = "envelope-o"
    weight = 5

#[[menu.icon]]
    #url = "https://github.com/username/"
    #name = "github"
    #weight = 2

#[[menu.icon]]
    #url = "https://twitter.com/username/"
    #name = "twitter"
    #weight = 3

#[[menu.icon]]
    #url = "https://www.linkedin.com/in/username/"
    #name = "linkedin"
    #weight = 4

#[[menu.icon]]
    #url = "https://www.stackoverflow.com/username/"
    #name = "stack-overflow"
    #weight = 5
